// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TypingTest.Data;

#nullable disable

namespace TypingTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410213525_UpdateElitePassages")]
    partial class UpdateElitePassages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TypingTest.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TypingTest.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasPrecision(5, 2)
                        .HasColumnType("float(5)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectKeystrokes")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<int>("TotalKeystrokes")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WordCountTarget")
                        .HasColumnType("int");

                    b.Property<int>("WordPassageId")
                        .HasColumnType("int");

                    b.Property<int>("Wpm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordPassageId");

                    b.HasIndex("Wpm", "CompletedAt");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("TypingTest.Models.WordPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.ToTable("WordPassages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "the cat sat on the mat",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "First Steps",
                            WordCount = 5
                        },
                        new
                        {
                            Id = 2,
                            Content = "a big red car drove down the road",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "Simple Words",
                            WordCount = 7
                        },
                        new
                        {
                            Id = 3,
                            Content = "the sun is hot and the sky is blue",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "Basic Phrases",
                            WordCount = 8
                        },
                        new
                        {
                            Id = 4,
                            Content = "the dog ran across the yard and jumped over the fence into the garden",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "Simple Intro",
                            WordCount = 13
                        },
                        new
                        {
                            Id = 5,
                            Content = "she woke up early made some tea and sat by the window to watch the birds",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "Daily Life",
                            WordCount = 15
                        },
                        new
                        {
                            Id = 6,
                            Content = "the boy kicked the ball and it flew high into the air before landing in the grass",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "Short Story",
                            WordCount = 17
                        },
                        new
                        {
                            Id = 7,
                            Content = "the best way to get better at typing is to keep practicing every day even when it feels slow and difficult",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 3,
                            Title = "Keep Going",
                            WordCount = 21
                        },
                        new
                        {
                            Id = 8,
                            Content = "when you focus on what you are doing and take your time the words will start to flow more easily from your fingers",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 3,
                            Title = "Stay Focused",
                            WordCount = 23
                        },
                        new
                        {
                            Id = 9,
                            Content = "sitting up straight and keeping your eyes on the screen instead of your hands will help you type much faster over time",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 3,
                            Title = "Good Habits",
                            WordCount = 22
                        },
                        new
                        {
                            Id = 10,
                            Content = "getting better at anything takes time and effort but if you stick with it and do not give up you will be surprised at how much you can improve in just a few weeks",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 4,
                            Title = "The Journey",
                            WordCount = 34
                        },
                        new
                        {
                            Id = 11,
                            Content = "every time you make a mistake it is a chance to learn and do better next time so do not get frustrated just take a breath and try again from the beginning",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 4,
                            Title = "Keep Trying",
                            WordCount = 33
                        },
                        new
                        {
                            Id = 12,
                            Content = "the key to typing well under pressure is to stay calm and not rush because when you slow down just a little your accuracy goes up and your overall speed improves too",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 4,
                            Title = "Stay Calm",
                            WordCount = 34
                        },
                        new
                        {
                            Id = 13,
                            Content = "a skilled typist does not just type fast they type with control knowing exactly when to slow down to avoid mistakes that would cost them more time to fix than they saved by rushing",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 5,
                            Title = "Speed and Accuracy",
                            WordCount = 35
                        },
                        new
                        {
                            Id = 14,
                            Content = "confidence plays a big role in how well you perform under pressure so trust your training keep your posture steady and let your fingers do what they have been trained to do",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 5,
                            Title = "The Right Mindset",
                            WordCount = 33
                        },
                        new
                        {
                            Id = 15,
                            Content = "there is a state where typing feels almost effortless where your hands move without thinking and the words appear on the screen as fast as you can read them in your head",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 5,
                            Title = "Finding Flow",
                            WordCount = 34
                        },
                        new
                        {
                            Id = 16,
                            Content = "at this level raw speed is no longer the only goal what matters now is the ability to maintain high accuracy over longer passages without losing focus or letting small errors break your rhythm and slow you down",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 6,
                            Title = "Beyond Speed",
                            WordCount = 40
                        },
                        new
                        {
                            Id = 17,
                            Content = "after thousands of hours of practice your fingers begin to know where every key is without you having to think about it and that is when typing becomes less of a skill and more of a reflex that never fades",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 6,
                            Title = "Muscle Memory",
                            WordCount = 42
                        },
                        new
                        {
                            Id = 18,
                            Content = "becoming truly great at typing is not about talent it is about showing up every day putting in the work and trusting that the small improvements you make each session will add up to something remarkable over time",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 6,
                            Title = "The Long Game",
                            WordCount = 40
                        },
                        new
                        {
                            Id = 19,
                            Content = "you have come a long way from where you started and every stage you cleared was proof that you had what it takes to keep going even when it was hard and now standing at the top you can look back and see just how far your fingers have carried you",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 7,
                            Title = "The Summit",
                            WordCount = 52
                        },
                        new
                        {
                            Id = 20,
                            Content = "mastery is not a destination you reach and then stop at it is a way of moving through the world with care and precision doing the small things right every time because you know that the small things are what everything else is built on",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 7,
                            Title = "Mastery Defined",
                            WordCount = 46
                        },
                        new
                        {
                            Id = 21,
                            Content = "this is where everything you have practiced comes together your speed your accuracy your focus and your patience all working as one so take a deep breath put your fingers on the keys and show the world what you are made of because you have earned this moment",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 7,
                            Title = "The Final Test",
                            WordCount = 49
                        },
                        new
                        {
                            Id = 22,
                            Content = "cryptographic algorithms rely on computational complexity to ensure that unauthorized decryption remains mathematically infeasible even with significant processing power distributed across multiple high performance systems simultaneously",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 8,
                            Title = "The Elite Path",
                            WordCount = 28
                        },
                        new
                        {
                            Id = 23,
                            Content = "electromagnetic interference can significantly degrade signal integrity in high frequency transmission lines requiring careful impedance matching and shielding techniques to maintain acceptable bit error rates across extended communication channels",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 8,
                            Title = "Controlled Power",
                            WordCount = 30
                        },
                        new
                        {
                            Id = 24,
                            Content = "neuroplasticity demonstrates that sustained cognitive engagement fundamentally restructures synaptic pathways enabling individuals to acquire sophisticated competencies that initially appeared incomprehensible through deliberate incremental exposure and reinforcement",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 8,
                            Title = "No Shortcuts",
                            WordCount = 27
                        },
                        new
                        {
                            Id = 25,
                            Content = "the thermodynamic irreversibility of spontaneous processes is quantified through entropic calculations that reveal the fundamental asymmetry between forward and reverse reactions under equilibrium conditions demonstrating why perpetual motion machines violate established physical principles unconditionally",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "Legendary Focus",
                            WordCount = 35
                        },
                        new
                        {
                            Id = 26,
                            Content = "Byzantine fault tolerance in distributed computing systems requires sophisticated consensus mechanisms capable of maintaining operational integrity even when a significant proportion of participating nodes behave arbitrarily maliciously or transmit contradictory information to different recipients simultaneously",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "Beyond Limits",
                            WordCount = 36
                        },
                        new
                        {
                            Id = 27,
                            Content = "pharmacokinetic variability among patient populations complicates standardized dosing protocols requiring clinicians to account for polymorphic metabolic enzymes hepatic function renal clearance rates and potential drug interactions that collectively influence bioavailability and therapeutic efficacy unpredictably",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "The Long Road",
                            WordCount = 34
                        },
                        new
                        {
                            Id = 28,
                            Content = "stochastic gradient descent optimization algorithms navigate high dimensional non convex loss landscapes by iteratively adjusting parameter vectors in directions that minimize empirical risk while regularization techniques simultaneously constrain model complexity to prevent overfitting on finite training distributions with limited representational diversity",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "Grandmaster",
                            WordCount = 40
                        },
                        new
                        {
                            Id = 29,
                            Content = "quaternionic representations extend complex number theory into four dimensional algebras enabling compact parameterization of three dimensional rotational transformations that avoid gimbal lock singularities inherent in conventional Euler angle decompositions widely exploited in aerospace navigation and robotic kinematic chain computations",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "The Final Form",
                            WordCount = 40
                        },
                        new
                        {
                            Id = 30,
                            Content = "epigenetic modifications including cytosine methylation and histone acetylation dynamically regulate transcriptional accessibility without altering underlying nucleotide sequences demonstrating that heritable phenotypic variation can emerge through mechanisms entirely independent of conventional Mendelian genetic transmission across successive generations",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "Beyond the Summit",
                            WordCount = 38
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TypingTest.Models.TestResult", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypingTest.Models.WordPassage", "WordPassage")
                        .WithMany("TestResults")
                        .HasForeignKey("WordPassageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPassage");
                });

            modelBuilder.Entity("TypingTest.Models.ApplicationUser", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("TypingTest.Models.WordPassage", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
