// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TypingTest.Data;

#nullable disable

namespace TypingTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601131131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TypingTest.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TypingTest.Models.GameScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("BestWpm")
                        .HasColumnType("integer");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfectHits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wave")
                        .HasColumnType("integer");

                    b.Property<int>("WordsCompleted")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("GameType", "Score");

                    b.ToTable("GameScores");
                });

            modelBuilder.Entity("TypingTest.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectKeystrokes")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKeystrokes")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCountTarget")
                        .HasColumnType("integer");

                    b.Property<int>("WordPassageId")
                        .HasColumnType("integer");

                    b.Property<int>("Wpm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WordPassageId");

                    b.HasIndex("Wpm", "CompletedAt");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("TypingTest.Models.WordPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.ToTable("WordPassages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "the cat sat on the mat",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "First Steps",
                            WordCount = 5
                        },
                        new
                        {
                            Id = 2,
                            Content = "a big red car drove down the road",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "Simple Words",
                            WordCount = 7
                        },
                        new
                        {
                            Id = 3,
                            Content = "the sun is hot and the sky is blue",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 1,
                            Title = "Basic Phrases",
                            WordCount = 8
                        },
                        new
                        {
                            Id = 4,
                            Content = "the dog ran across the yard and jumped over the low fence",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "Morning Walk",
                            WordCount = 12
                        },
                        new
                        {
                            Id = 5,
                            Content = "she woke up early made some tea and sat by the window",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "Daily Life",
                            WordCount = 12
                        },
                        new
                        {
                            Id = 6,
                            Content = "the boy kicked the ball and it flew high into the air",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 2,
                            Title = "After School",
                            WordCount = 12
                        },
                        new
                        {
                            Id = 7,
                            Content = "the best way to get better at typing is to keep practicing every single day even when it feels slow",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 3,
                            Title = "Keep Going",
                            WordCount = 18
                        },
                        new
                        {
                            Id = 8,
                            Content = "when you focus on what you are doing and take your time the words will start to flow more easily",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 3,
                            Title = "Stay Focused",
                            WordCount = 18
                        },
                        new
                        {
                            Id = 9,
                            Content = "sitting up straight and keeping your eyes on the screen instead of your hands will help you type faster",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 3,
                            Title = "Good Habits",
                            WordCount = 17
                        },
                        new
                        {
                            Id = 10,
                            Content = "getting better at anything takes time and effort but if you stick with it and do not give up you will be surprised at how much you can improve",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 4,
                            Title = "The Journey",
                            WordCount = 25
                        },
                        new
                        {
                            Id = 11,
                            Content = "every time you make a mistake it is a chance to learn and do better next time so do not get frustrated just take a breath and try again",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 4,
                            Title = "Keep Trying",
                            WordCount = 25
                        },
                        new
                        {
                            Id = 12,
                            Content = "the key to typing well under pressure is to stay calm and not rush because when you slow down a little your accuracy goes up and your speed improves too",
                            Difficulty = 0,
                            IsActive = true,
                            Stage = 4,
                            Title = "Stay Calm",
                            WordCount = 26
                        },
                        new
                        {
                            Id = 13,
                            Content = "a skilled typist does not just type fast they type with control knowing exactly when to slow down to avoid mistakes that would cost them more time to fix than they saved by rushing through the passage",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 5,
                            Title = "Speed and Accuracy",
                            WordCount = 32
                        },
                        new
                        {
                            Id = 14,
                            Content = "confidence plays a big role in how well you perform under pressure so trust your training keep your posture steady and let your fingers do what they have been trained to do without hesitation",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 5,
                            Title = "The Right Mindset",
                            WordCount = 31
                        },
                        new
                        {
                            Id = 15,
                            Content = "there is a state where typing feels almost effortless where your hands move without thinking and the words appear on the screen as fast as you can read them in your head and that is what you are aiming for",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 5,
                            Title = "Finding Flow",
                            WordCount = 35
                        },
                        new
                        {
                            Id = 16,
                            Content = "at this level raw speed is no longer the only goal what matters now is the ability to maintain high accuracy over longer passages without losing focus or letting small errors break your rhythm and slow you down considerably",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 6,
                            Title = "Beyond Speed",
                            WordCount = 38
                        },
                        new
                        {
                            Id = 17,
                            Content = "after thousands of repetitions your fingers begin to know where every key is without you having to think about it and that is when typing becomes less of a skill and more of a reflex that never fades no matter how much time passes",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 6,
                            Title = "Muscle Memory",
                            WordCount = 40
                        },
                        new
                        {
                            Id = 18,
                            Content = "becoming truly great at typing is not about talent it is about showing up every day putting in the work and trusting that the small improvements you make each session will add up to something remarkable over a long period of time",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 6,
                            Title = "The Long Game",
                            WordCount = 38
                        },
                        new
                        {
                            Id = 19,
                            Content = "you have come a long way from where you started and every stage you cleared was proof that you had what it takes to keep going even when it was hard and now you can look back and see just how far your fingers have carried you on this journey",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 7,
                            Title = "The Summit",
                            WordCount = 48
                        },
                        new
                        {
                            Id = 20,
                            Content = "mastery is not a destination you reach and then stop at it is a way of moving through the world with care and precision doing the small things right every single time because you know deep down that the small things are what everything else is ultimately built upon",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 7,
                            Title = "Mastery Defined",
                            WordCount = 46
                        },
                        new
                        {
                            Id = 21,
                            Content = "this is where everything you have practiced starts to come together your speed your accuracy your focus and your patience all working as one fluid motion so take a deep breath put your fingers on the keys and show the screen what you are made of because you have worked hard to get here",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 7,
                            Title = "Ready to Rise",
                            WordCount = 50
                        },
                        new
                        {
                            Id = 22,
                            Content = "the difference between an average typist and an exceptional one is not found in moments of peak performance but rather in the consistency of output maintained across long sessions when focus begins to waver and the temptation to rush becomes harder to resist with every passing minute of concentrated effort",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 8,
                            Title = "Consistent Output",
                            WordCount = 55
                        },
                        new
                        {
                            Id = 23,
                            Content = "performing well under pressure is a skill that must be developed deliberately through repeated exposure to challenging conditions because the body and mind both need time to learn that the elevated heart rate and heightened focus that come with difficult situations are assets rather than obstacles to be feared",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 8,
                            Title = "Under Pressure",
                            WordCount = 54
                        },
                        new
                        {
                            Id = 24,
                            Content = "there is enormous value in trusting the process even when results are slow to appear because every session spent at the keyboard is quietly building the neural pathways and muscle memory that will eventually allow your fingers to move with a speed and accuracy that once seemed completely out of reach but is now becoming your new normal",
                            Difficulty = 1,
                            IsActive = true,
                            Stage = 8,
                            Title = "The Process",
                            WordCount = 58
                        },
                        new
                        {
                            Id = 25,
                            Content = "algorithmic problem solving requires the practitioner to decompose complex challenges into discrete manageable components that can be addressed systematically using established computational patterns while simultaneously evaluating the trade offs between processing efficiency memory utilization and implementation complexity across diverse hardware architectures",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "Computational Thinking",
                            WordCount = 46
                        },
                        new
                        {
                            Id = 26,
                            Content = "neuroplasticity research demonstrates that sustained cognitive engagement fundamentally restructures synaptic connectivity enabling individuals to acquire sophisticated competencies that initially appeared incomprehensible through deliberate incremental exposure combined with consistent reinforcement of newly established neural pathways across extended learning periods",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "Neural Pathways",
                            WordCount = 44
                        },
                        new
                        {
                            Id = 27,
                            Content = "electromagnetic interference can significantly degrade signal integrity in high frequency transmission lines requiring careful impedance matching and comprehensive shielding techniques to maintain acceptable bit error rates across extended communication channels operating in electrically noisy industrial environments with multiple competing interference sources",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 9,
                            Title = "Signal Integrity",
                            WordCount = 48
                        },
                        new
                        {
                            Id = 28,
                            Content = "modern cryptographic protocols rely on the computational intractability of specific mathematical problems such as integer factorization and discrete logarithms to ensure that unauthorized decryption remains infeasible even when adversaries possess substantial distributed processing resources operating continuously across geographically dispersed server infrastructure for extended periods exceeding several decades",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "Cryptographic Systems",
                            WordCount = 56
                        },
                        new
                        {
                            Id = 29,
                            Content = "the thermodynamic irreversibility of spontaneous natural processes is rigorously quantified through entropic calculations that reveal the fundamental asymmetry between forward and reverse reactions under equilibrium conditions conclusively demonstrating why perpetual motion machines of both the first and second kind necessarily violate well established physical conservation principles without exception",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "Thermodynamic Laws",
                            WordCount = 58
                        },
                        new
                        {
                            Id = 30,
                            Content = "Byzantine fault tolerance in distributed computing systems requires sophisticated consensus mechanisms capable of maintaining full operational integrity even when a significant proportion of participating nodes behave arbitrarily maliciously or simultaneously transmit contradictory information to different recipients undermining the reliability guarantees that mission critical infrastructure depends upon absolutely",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 10,
                            Title = "Distributed Consensus",
                            WordCount = 60
                        },
                        new
                        {
                            Id = 31,
                            Content = "pharmacokinetic variability among diverse patient populations significantly complicates standardized therapeutic dosing protocols requiring clinicians to carefully account for polymorphic metabolic enzyme expression hepatic functional capacity renal clearance rates age related physiological changes and potential drug interactions that collectively influence bioavailability and therapeutic efficacy in ways that remain difficult to predict reliably without comprehensive genetic profiling",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 11,
                            Title = "Pharmacokinetics",
                            WordCount = 66
                        },
                        new
                        {
                            Id = 32,
                            Content = "the Copenhagen interpretation of quantum mechanical wave function collapse remains philosophically contentious among theoretical physicists because it implies that observation itself plays a fundamental role in determining physical reality suggesting that unmeasured quantum systems exist in genuine superpositions of mutually exclusive states rather than simply reflecting incomplete knowledge about predetermined classical outcomes that existed independently of measurement",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 11,
                            Title = "Quantum Mechanics",
                            WordCount = 68
                        },
                        new
                        {
                            Id = 33,
                            Content = "the transmission mechanisms through which central bank monetary policy decisions propagate through complex interconnected financial systems to ultimately influence real economic variables such as employment inflation and productive investment involve numerous intermediate channels including credit availability yield curve dynamics currency valuation expectations formation and wealth effects operating across multiple time horizons simultaneously with varying degrees of predictability",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 11,
                            Title = "Macroeconomic Policy",
                            WordCount = 70
                        },
                        new
                        {
                            Id = 34,
                            Content = "epigenetic modifications including cytosine methylation patterns and histone acetylation states dynamically regulate transcriptional accessibility across the genome without altering the underlying nucleotide sequences themselves conclusively demonstrating that heritable phenotypic variation can emerge through molecular mechanisms entirely independent of conventional Mendelian genetic transmission providing compelling evidence that environmental exposures experienced by parents can directly influence gene expression patterns in subsequent generations",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 12,
                            Title = "Epigenetic Inheritance",
                            WordCount = 72
                        },
                        new
                        {
                            Id = 35,
                            Content = "stochastic gradient descent optimization algorithms navigate extremely high dimensional non convex loss landscapes by iteratively adjusting parameter vectors in directions that approximately minimize empirical risk on randomly sampled data subsets while carefully tuned regularization techniques simultaneously constrain overall model complexity to prevent catastrophic overfitting on finite training distributions that may not adequately represent the full diversity of real world deployment conditions",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 12,
                            Title = "Stochastic Optimization",
                            WordCount = 74
                        },
                        new
                        {
                            Id = 36,
                            Content = "the extended evolutionary synthesis incorporates epigenetic inheritance developmental plasticity niche construction and multilevel selection into the conceptual framework of evolutionary biology recognizing that phenotypic variation can arise through mechanisms operating across multiple biological levels and timescales simultaneously challenging the gene centric perspective that dominated theoretical evolutionary biology throughout the latter half of the twentieth century and continuing to generate productive empirical research programs",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 12,
                            Title = "Evolutionary Biology",
                            WordCount = 76
                        },
                        new
                        {
                            Id = 37,
                            Content = "quaternionic representations extend complex number theory into four dimensional non commutative algebras enabling remarkably compact parameterization of three dimensional rotational transformations that completely avoid the gimbal lock singularities inherent in conventional Euler angle decompositions which are widely exploited in aerospace navigation systems robotic kinematic chain computations computer graphics rendering pipelines and inertial measurement unit fusion algorithms where computational efficiency and numerical stability across all possible orientations are simultaneously critical requirements",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 13,
                            Title = "Quaternion Algebra",
                            WordCount = 80
                        },
                        new
                        {
                            Id = 38,
                            Content = "the Sapir Whorf hypothesis in its strong formulation proposes that the grammatical structures and lexical categories present in a speaker's native language fundamentally constrain the range of thoughts that speaker is capable of forming thereby suggesting that cognitive architecture varies systematically across linguistic communities in ways that go beyond mere surface level differences in expressive convention to reflect genuinely distinct ways of organizing and categorizing perceptual experience of the shared physical world",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 13,
                            Title = "Linguistic Relativity",
                            WordCount = 82
                        },
                        new
                        {
                            Id = 39,
                            Content = "Shannon entropy provides a rigorous mathematical framework for quantifying the average information content of messages drawn from probabilistic source distributions enabling precise theoretical bounds on lossless data compression ratios and establishing fundamental capacity limits for reliable communication across noisy transmission channels that hold regardless of the specific encoding schemes or error correction strategies employed by system designers working within the constraints imposed by the channel's statistical characteristics",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 13,
                            Title = "Information Theory",
                            WordCount = 84
                        },
                        new
                        {
                            Id = 40,
                            Content = "the hard problem of consciousness as articulated by David Chalmers draws a fundamental distinction between the relatively tractable functional and behavioral aspects of mental life that neuroscience is progressively explaining through mechanistic accounts of neural information processing and the genuinely mysterious explanatory gap that separates any complete physical description of brain activity from the subjective phenomenal qualities of conscious experience the intrinsic felt character of sensations emotions and thoughts that seems to resist reduction to purely objective third person scientific description however detailed and comprehensive",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 14,
                            Title = "Consciousness Studies",
                            WordCount = 90
                        },
                        new
                        {
                            Id = 41,
                            Content = "the Poincare conjecture which was finally resolved by Grigori Perelman through his application of Richard Hamilton's Ricci flow with surgery technique asserts that any closed three dimensional manifold in which every loop can be continuously contracted to a single point is necessarily topologically equivalent to the standard three sphere representing a profound insight into the relationship between local geometric constraints and global topological structure that has far reaching implications for our mathematical understanding of the possible shapes of the physical universe at cosmological scales",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 14,
                            Title = "Topology and Space",
                            WordCount = 92
                        },
                        new
                        {
                            Id = 42,
                            Content = "the adaptive immune system achieves its remarkable capacity for highly specific pathogen recognition through a stochastic process of somatic recombination that generates an astronomically large repertoire of antigen binding receptor configurations during lymphocyte development followed by clonal selection mechanisms that amplify cells bearing receptors with sufficient affinity for encountered pathogens while simultaneously establishing immunological memory populations that enable dramatically accelerated and intensified secondary responses upon subsequent exposure to the same or closely related antigenic determinants",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 14,
                            Title = "Immune System Dynamics",
                            WordCount = 88
                        },
                        new
                        {
                            Id = 43,
                            Content = "Einstein's general theory of relativity reconceptualizes gravitational interaction not as a conventional force acting instantaneously across distance in the manner of Newtonian mechanics but rather as a manifestation of the curvature of four dimensional spacetime geometry induced by the presence of mass and energy distributions with freely falling objects following geodesic paths through this curved manifold that appear as accelerated trajectories when described from the perspective of non inertial reference frames anchored to massive bodies thereby unifying the previously separate phenomena of inertia and gravitation within a single elegant geometric framework that has withstood every experimental test devised over more than a century",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 15,
                            Title = "General Relativity",
                            WordCount = 104
                        },
                        new
                        {
                            Id = 44,
                            Content = "the P versus NP problem which stands as arguably the most consequential unresolved question in theoretical computer science asks whether every computational decision problem whose solutions can be verified in polynomial time by a deterministic Turing machine can also be solved in polynomial time by such a machine with the widespread belief that P does not equal NP reflecting the empirical observation that many practically important optimization and search problems appear to require exponentially growing computational resources as input size increases despite the fact that proposed solutions to specific instances can be checked with remarkable efficiency suggesting a profound and fundamental asymmetry between solution generation and solution verification",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 15,
                            Title = "Complexity Theory",
                            WordCount = 106
                        },
                        new
                        {
                            Id = 45,
                            Content = "Karl Popper's criterion of falsifiability as the demarcation principle separating genuinely scientific theories from metaphysical speculation has proven enormously influential in shaping how scientists and philosophers understand the epistemological foundations of empirical inquiry yet the criterion itself faces serious philosophical challenges from the Duhem Quine thesis which demonstrates that individual theoretical hypotheses cannot be tested in isolation from the auxiliary assumptions that must be invoked to derive observable predictions meaning that experimental disconfirmation always leaves open the possibility of preserving a favored central hypothesis by revising peripheral background assumptions rather than accepting refutation",
                            Difficulty = 2,
                            IsActive = true,
                            Stage = 15,
                            Title = "Philosophy of Science",
                            WordCount = 108
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TypingTest.Models.GameScore", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TypingTest.Models.TestResult", b =>
                {
                    b.HasOne("TypingTest.Models.ApplicationUser", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypingTest.Models.WordPassage", "WordPassage")
                        .WithMany("TestResults")
                        .HasForeignKey("WordPassageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WordPassage");
                });

            modelBuilder.Entity("TypingTest.Models.ApplicationUser", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("TypingTest.Models.WordPassage", b =>
                {
                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
